# Generated by Django 3.2.5 on 2022-03-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BAAModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('epoch', models.IntegerField(default=0)),
                ('accuracy_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BAA.algorithm')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='BAAModel_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.URLField(default='')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BAA.baamodel')),
            ],
        ),
    ]
